# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Interpreted, interactive, object-oriented programming language
brew "python@3.14"
# Client library for huggingface.co hub
brew "hf"
# NCurses Disk Usage
brew "ncdu"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Modernized, complete, self-contained TeX/LaTeX engine
brew "tectonic"
# Check your $HOME for unwanted files and directories
brew "xdg-ninja", args: ["HEAD"]
cask "font-terminus"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
